### ISSUE TITLE
Lost columns when attribute is not returned from API

### ISSUE THREAD

**Issue by bn8959** [derpenstiltskin/connectwise-powerbi#1]
The ConnectWise Manage API will not return attributes if their value is null. Therefore columns can be lost if the first record returned is missing a value due to it being null - all subsequent rows then are missing those columns.
As data changes over time, the first record can therefore be missing different columns at different times - this causes frequent refresh errors.

Either we need to be able to specify the full list of columns, and the returned table will contain all these columns, even if the API dosent return any data for them. Or the script would need to add additional columns to the returned table if new fields are returned in subsequent result - although depending on the query this could still result in columns going missing.

**Comment by derpenstiltskin** [comment]
This has been fixed in [a744be6](https://github.com/derpenstiltskin/connectwise-powerbi/commit/a744be6c9435c1dd5faaa9c0f32f1e1e1adc53e8) / [v1.1.0](https://github.com/derpenstiltskin/connectwise-powerbi/releases/tag/v1.1.0). The query now generates a distinct list of the field names from all of the records in the response from the API, then uses that list to create the table columns.
